<?php
/**
 * @file
 * Drupal 7 module that provides integration with a recent TinyMCE editor.
 */

/**
 * Implements hook_library().
 */
function tinymcebackport_library() {
  $lib_path = drupal_get_path('module', 'tinymcebackport') . '/libraries/tinymce/js/tinymce/tinymce.min.js';
  $libraries['bp.tinymce'] = array(
    'title' => 'TinyMCE',
    'website' => 'https://www.tiny.cloud/',
    'version' => '7.4.1',
    'js' => array(
      $lib_path => array('group' => JS_LIBRARY, 'preprocess' => FALSE),
    ),
  );
  return $libraries;
}

/**
 * Implements hook_library_alter().
 */
function tinymcebackport_library_alter(&$libraries, $module) {
  if ($module == 'media') {
    // Override a method from Drupal.media.browser, which breaks our
    // media integration.
    $path = drupal_get_path('module', 'tinymcebackport') . '/js/tinymce-drupalmedia.js';
    $libraries['media_browser_page']['js'][$path] = array('group' => 0);
  }
}

/**
 * Implements hook_element_info_alter().
 */
function tinymcebackport_element_info_alter(&$types) {
  $types['text_format']['#pre_render'][] = '_tinymcebackport_pre_render_text_format';
}

/**
 * Custom pre_render callback.
 */
function _tinymcebackport_pre_render_text_format(array $element) {
  if (!isset($element['#format'])) {
    return $element;
  }
  // Ignore summary and stuff.
  if (!isset($element['value'])) {
    return $element;
  }

  // Always get rid of grippie.
  $element['value']['#resizable'] = FALSE;

  $element['#attached']['library'][] = array('tinymcebackport', 'bp.tinymce');
  $js_path = drupal_get_path('module', 'tinymcebackport') . '/js/tinymcebackport.js';
  $element['#attached']['js'][$js_path] = array();

  $enabled_formats = _tinymcebackport_get_enabled_formats();
  $js_settings = array(
    'tinymcebackport' => array(),
  );
  foreach ($enabled_formats as $enabled_format) {
    $js_settings['tinymcebackport'][$enabled_format] = array(
      'options' => _tinymcebackport_get_default_options($enabled_format),
    );
  }
  $element['#attached']['js'][] = array(
    'data' => $js_settings,
    'type' => 'setting',
  );

  return $element;
}

/**
 * Custom callback for default editor options.
 */
function _tinymcebackport_get_default_options($format) {
  global $language;
  $options = array(
    'branding' => FALSE,
    'promotion' => FALSE,
    'license_key' => 'gpl',
    'language' => $language->language,
    'browser_spellcheck' => TRUE,
    'entity_encoding' => 'raw',
    'convert_urls' => FALSE,
    'paste_data_images' => FALSE,
    'images_file_types' => 'jpeg,jpg,png,gif,webp',
    'file_picker_types' => 'file image',
    'min_height' => 300,
    'menubar' => FALSE,
    'plugins' => 'lists link image autoresize imgalign',
    'toolbar' => 'bold italic blockquote styles bullist numlist alignleft aligncenter alignright link unlink image removeformat',
  );

  // Not a built-in option, but a custom one for the imgalign plugin, which also
  // takes care of registering it.
  $options['image_align_classes'] = array(
    'left' => 'image-left',
    'center' => 'image-center',
    'right' => 'image-right',
  );

  $path = base_path() . drupal_get_path('module', 'tinymcebackport');
  $options['content_css'] = array(
    $path . '/css/tinymcebackport-content.css',
  );
  $options['external_plugins'] = array(
    'imgalign' => $path . '/plugins/imgalign/plugin.js',
  );
  if (module_exists('imce') && imce_access()) {
    $options['external_plugins']['imce'] = $path . '/plugins/imce/plugin.js';
    $options['plugins'] .= ' imce';
    $options['imceUrl'] = base_path() . 'imce?app=tinymce|sendto@tinymceImceResponseHandler';
  }
  // Rudimentary Media module support, but only if IMCE isn't available.
  elseif (module_exists('media') && user_access('access media browser')) {
    $options['external_plugins']['drupalmedia'] = $path . '/plugins/drupalmedia/plugin.js';
    $options['plugins'] .= ' drupalmedia';
    $options['mediaBrowseUrl'] = url('media/browser', array(
      'query' => array(
        'render' => 'media-popup',
        // Get rid of upload plugin, which works - but with awkward UX.
        'enabledPlugins' => array(
          'media_default--media_browser_my_files',
          'media_default--media_browser_1',
        ),
      ),
    ));
  }

  $options['formats'] = _tinymcebackport_get_format_settings();

  // Allow modules to modify the options.
  drupal_alter('tinymcebackport_options', $options, $format);

  return $options;
}

/**
 * Helper function to return some format settins to prevent inline styles.
 */
function _tinymcebackport_get_format_settings() {
  $formats = array();
  // Text align with classes only. The theme's supposed to provide styles.
  $align_selector = 'p,h1,h2,h3,h4,h5,h6,div';
  $formats['alignleft'] = array(
    array(
      'selector' => $align_selector,
      'classes' => 'text-align-left',
    ),
  );
  $formats['aligncenter'] = array(
    array(
      'selector' => $align_selector,
      'classes' => 'text-align-center',
    ),
  );
  $formats['alignright'] = array(
    array(
      'selector' => $align_selector,
      'classes' => 'text-align-right',
    ),
  );
  $formats['alignjustify'] = array(
    array(
      'selector' => $align_selector,
      'classes' => 'text-align-justify',
    ),
  );
  // Set tag as default for underline (instead of style).
  $formats['underline'] = array(
    array(
      'inline' => 'u',
    ),
  );
  return $formats;

}

/**
 * Callback to get formats, this editor's enabled for.
 */
function _tinymcebackport_get_enabled_formats() {
  $enabled = array('filtered_html');

  // Allow modules to modify enabled formats.
  drupal_alter('tinymcebackport_enabled_formats', $enabled);
  // Reset keys, so js doesn't choke.
  return array_values($enabled);
}
